openapi: 3.0.3
info:
  title: OpenAPI Course
  description: Specification for OpenAPI Course
  termsOfService: https://example.com/terms/
  version: 1.0.0
  contact:
    name: Ivo Eersels
    url: https://github.com/colwynB2K
    email: ivo.eersels@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://dev.example.com
    description: Development Server
  - url: https://qa/example.com
    description: QA Server
  - url: https://prod.example.com
    description: Production Server
paths:
  /v1/customers:
    get:
      summary: List Customers
      description: Get a list of customers in the system
      tags:
        - Customers
      operationId: v1ListCustomers
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"
    post:
      summary: New Customer
      description: Create a new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '201':
          description: Customer Created
  /v1/customers/{customerId}:
    get:
      summary: Get Customer by id
      description: Get a single **Customer** by its id value.
      tags:
        - Customers
      operationId: v1GetCustomerById
      parameters:
        - name: customerId
          in: path
          description: Customer Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
           description: Found Customer
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Customer"
  /v1/beers:
    get:
      summary: List Beers
      description: List all beers in the system.
      tags:
        - Beers
      operationId: v1ListBeers
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
      responses:
        200:
          description: List of Beers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BeerPagedList"
        404:
          description: No Beers found (the end is near!)
  /v1/beers/{beerId}:
    get:
      summary: Get Beer by id
      description: Get a single Beer by its id value.
      tags:
        - Beers
      operationId: v1GetBeerById
      parameters:
        - name: beerId
          in: path
          description: Beer Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Found Beer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Beer"
components:
  schemas:
    Address:
      type: object
      properties:
        line1:
          type: string
          example: 123 Main
        line2:
          type: string
          example: Room 503
        city:
          type: string
          example: St Pete
        stateCode:
          type: string
          description: Two letter state code
          minLength: 2
          maxLength: 2
          enum:
            - AK
            - AL
            - AR
            - AZ
            - CA
        zipcode:
          type: string
          example: 33701
    Customer:
      type: object
      description: Customer object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          description: First Name
          type: string
          minLength: 2
          maxLength: 100
          example: "John"
        lastName:
          description: Last Name
          type: string
          minLength: 2
          maxLength: 100
          example: "Rambo"
        address:
          $ref: "#/components/schemas/Address"
    CustomerList:
      type: array
      minItems: 1
      maxItems: 100
      items:
        $ref: "#/components/schemas/Customer"
    Brewery:
      description: Brewery information
      type: object
      properties:
        name:
          description: Brewery Name
          type: string
          example: "InBev"
        location:
          description: Location
          type: string
          example: "Alken, Belgium"
    Beer:
      type: object
      description: Beer object
      properties:
        id:
          type: string
          format: uuid
        name:
          description: Name
          type: string
          example: "Cristal Alken"
        style:
          description: Style
          type: string
          enum:
            - ALE
            - PALE_ALE
            - IPA
            - WHEAT
            - LAGER
          example: "ALE"
        upc:
          description: UPC
          type: string
          example: "123456"
        price:
          description: Price in Euro per 33cl
          type: number
          example: 2.50
        stock:
          description: Stock quantity
          type: integer
          example: 666
        brewery:
          $ref: "#/components/schemas/Brewery"
    BeerList:
      type: array
      minItems: 1
      maxItems: 100
      items:
        $ref: "#/components/schemas/Beer"
    BeerPagedList:
      type: object
      allOf:  # The response must consist only of PagedResponse objects
        - $ref: "#/components/schemas/PagedResponse"
      properties:
        content:  # Specify that it will be a paged response containing a list of Beer objects
          $ref: "#/components/schemas/BeerList"
    PagedResponse:
      type: object
      properties:
        pageable:
          type: object
          properties:
            sort:
              type: object
              properties:
                sorted:
                  type: boolean
                unsorted:
                  type: boolean
            offset:
              type: integer
              format: int32
            pageNumber:
              type: integer
              format: int32
            pageSize:
              type: integer
              format: int32
            paged:
              type: boolean
            unpaged:
              type: boolean
  parameters:
    PageNumber:
      name: pageNumber
      in: query
      description: Page Number
      schema:
        type: integer
        format: int32
        default: 1
    PageSize:
      name: pageSize
      in: query
      description: Page Size
      required: false
      schema:
        type: integer
        format: int32
        default: 25